
#ifndef _RCC_INTERFACE_H
#define _RCC_INTERFACE_H

#include "STD_TYPES.h"

void MCAL_RCC_void_InitSysClock();
void MCAL_RCC_void_EnableClock(u8_t Bus_ID , u8_t Peripheral_ID);
void MCAL_RCC_void_DisableClock(u8_t Bus_ID , u8_t Peripheral_ID);

typedef enum{RCC_AHP, RCC_APB1 ,RCC_APB2} RCC_BUS_CONFIG;
typedef enum{RCC_HSE_CRYSTAL, RCC_HSE_RC, RCC_HSI, RCC_PLL}RCC_CLOCK_TYPES;
typedef enum{RCC_PLL_IN_HSI_DIV_2, RCC_PLL_IN_HSE_DIV_2 ,RCC_PLL_IN_HSE}RCC_PLL_OPTIONS;

typedef enum{HSION,HSIRDY,R0,HSITRIM0,HSITRIM1,HSITRIM2,HSITRIM3,HSITRIM4,HSICAL0,HSICAL1,HSICAL2,HSICAL3,HSICAL4,HSICAL5,HSICAL6,HSICAL7,HSEON,HSERDY,HSEBYP,CSSON,R1,R2,R3,R4,PULLON,PULLRDY}CR_REGISTER_t;
typedef enum{SW0,SW1,SWS0,SWS1,HPRE0,HPRE1,HPRE2,HPRE3,PPRE10,PPRE11,PPRE12,PPRE20,PPRE21,PPRE22,ADCPRE0,ADCPRE1,PLLSRC,PLLXTPRE,PULLMUL0,PULLMUL1,PULLMUL2,PULLMUL3,USBBRE,R5,MCO0,MCO1,MCO2}CFGR_REGISTER_t;


#endif
